app:
  port: 8000
  host: 0.0.0.0
  environment: 'development'

auth:
  jwtSignMode: jwks
  jwtMap: 
    - sid:userId
    - email:email
    - roles:roles
  rolesClaim: "roles"
  headerPrefix: "X-GTW-AUTH-"
  
  outProp: $auth
  issuer: https://login.transfeero.com/realms/transfeero
  tokenUrl: https://login.transfeero.com/realms/transfeero/protocol/openid-connect/token
  jwksUri: https://login.transfeero.com/realms/transfeero/protocol/openid-connect/certs
  algorithms:
    - "RS256"
  clientId: "admin"
  #clientSecret:
  #audience:
  scopes:
    - "openid"
    - "profile"

broker:
  name: "rabbitmq"
  uri: "amqp://amqp.transfeero-staging.com:5672"
  defaultSubscribeErrorBehavior: "ack"
  defaultPublishErrorBehavior: "reject"
  connectionManagerOptions:
    heartbeatIntervalInSeconds: 60
    reconnectTimeInSeconds: 60
    connectionOptions:
      clientProperties:
        connection_name: "nestjs-amqp-sample"
      credentials:
        mechanism: PLAIN
        username: guest
        password: guest

  exchanges:
    - name: "local-test"
      type: "direct"
      createExchangeIfNotExists: true
      options:
        durable: true
        autoDelete: false
        internal: false
    - name: sample-bst
      type: "topic"
      createExchangeIfNotExists: true
      options:
        durable: true
        autoDelete: false

  queues:
    - name: "local-test"
      createQueueIfNotExists: true
      exchange: local-test
      routingKey: local-test
      options:
        durable: true
        autoDelete: false
        exclusive: false

microservices:
  topics:
    - name: local-test
      queue: local-test
      rpc: true
    - name: sample-bst
      exchange: sample-bst
      routingKey: broadcast/#

gateway:
  mode: gateway
  paths:
    - name: local-test
      auth: false
      # roles:
      #   - "admin"
      method: POST
      dataSource: body
      path: /local-test/test-01
      topic: local-test
      action: test-01
      mode: "rpc"
    - name: local-test
      auth: false
      # roles:
      #   - "admin"
      method: POST
      dataSource: body
      path: /local-test/test-02
      topic: local-test
      action: test-02
      mode: "rpc"