app:
  port: 80
  host: 0.0.0.0
  environment: "development"

auth-providers: []

broker:
  name: "rabbitmq"
  uri: "amqp://amqp.riolabs.net:5672/whatsapp"
  defaultSubscribeErrorBehavior: "ack"
  defaultPublishErrorBehavior: "reject"
  connectionManagerOptions:
    heartbeatIntervalInSeconds: 60
    reconnectTimeInSeconds: 60
    connectionOptions:
      clientProperties:
        connection_name: "whatsapp-gateway"
      credentials:
        mechanism: PLAIN
        username: kYY265zjyM
        password: p98iko5aMIFCPf6z0REKQLgqtojbrej0

  exchanges:
    - name: wa.fanout
      type: "fanout"
      createExchangeIfNotExists: true
      options:
        durable: true
        autoDelete: false
        internal: false
    - name: gtw.config
      type: "direct"
      createExchangeIfNotExists: true
      options:
        durable: true
        autoDelete: false
        internal: false

  queues:
    - name: gtw.config
      createQueueIfNotExists: true
      exchange: gtw.config
      routingKey: gtw.config
      options:
        durable: true
        autoDelete: false
        exclusive: false

topics:
  - name: wa.fanout
    exchange: wa.fanout
    routingKey: "wa.fanout"
    mode: event
  - name: gtw.config
    exchange: gtw.config
    queue: gtw.config
    routingKey: gtw.config
    mode: rpc

gateway:
  events: []
  mode: gateway
  paths:
    - name: whatsapp-message
      method: POST
      dataSource: body
      path: /whatsapp
      topic: wa.fanout
      action: whatsapp-webhook-message
      mode: event
    - name: whatsapp-config
      method: GET
      dataSource: query
      path: /whatsapp
      topic: gtw.config
      action: whatsapp-webhook-verify
      mode: rpc

services:
  whatsapp:
    hookVerifyToken: demo123
